dist: xenial
language: python
python:
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"
cache: pip
install:
  - mkdir -p /home/travis/config
  - pip install -r requirements.txt
script:
  - python RSScrawler.py --port=9090 --config="/home/travis/config" --testlauf --log-level=DEBUG
