dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
allow_failures:
  - python: 3.8-dev
cache: pip
install:
  - mkdir -p /home/travis/config
  - mkdir -p /home/travis/jd2/folderwatch
  - pip install -r requirements.txt
script:
  - python RSScrawler.py --port=9090 --config="/home/travis/config" --jd-pfad="/home/travis/jd2" --testlauf --log-level=DEBUG
